@startuml
left to right direction

actor Configuratore as C

rectangle "GestoreEventi - Back-End V1" {


usecase "UC1: Login" as Login
usecase "UC2: Registrazione" as Reg
usecase "UC3: Primo Accesso:\nFissare Campi Base" as Primo
usecase "UC4: Visualizzare\nCampi e Categorie" as Vis

' --- AGGIUNTA CAMPI ---
usecase "UC5: Aggiungi\nCampo Comune" as ACC
usecase "UC10: Aggiungi\nCampo Specifico" as ACS
usecase "Aggiungi Campo" as AC

' --- RIMOZIONE CAMPI ---
usecase "UC6: Rimuovi\nCampo Comune" as RCC
usecase "UC11: Rimuovi\nCampo Specifico" as RCS
usecase "Rimuovi Campo" as RC

' --- MODIFICA OBBLIGATORIETÀ ---
usecase "UC7: Modifica Obbligatorietà\nCampo Comune" as MOCC
usecase "UC12: Modifica Obbligatorietà\nCampo Specifico" as MOCS
usecase "Modifica Obbligatorietà\nCampo" as MO

' --- CATEGORIE ---
usecase "UC8: Crea\nCategoria" as CreaCat
usecase "UC9: Rimuovi\nCategoria" as RimCat

Login <.. Reg : <<extend>>
Login <.. Primo : <<extend>>

ACC ..> AC : <<include>>
ACS ..> AC : <<include>>

RCC ..> RC : <<include>>
RCS ..> RC : <<include>>

MOCC ..> MO : <<include>>
MOCS ..> MO : <<include>>


}

C --> Login
C --> Vis
C --> ACC
C --> RCC
C --> MOCC
C --> CreaCat
C --> RimCat
C --> ACS
C --> RCS
C --> MOCS

@enduml
